*&---------------------------------------------------------------------*
*&  Include           ZQMI_CERTIFICATE_TOP
*&---------------------------------------------------------------------*

TABLES: LIPS, QALS, QAMR, QPMK, ZMAP_COA, AUSP, INOB.

DATA: BEGIN OF IT_DATA OCCURS 0,
        CHK TYPE C,
        VBELN LIKE LIPS-VBELN,
        POSNR LIKE LIPS-POSNR,
        CHARG LIKE LIPS-CHARG,
        MATNR LIKE LIPS-MATNR,
        WERKS LIKE LIPS-WERKS,
        UECHA LIKE LIPS-UECHA,
        NOMSR TYPE C LENGTH 30,
        ZZTYPE TYPE C LENGTH 30,
        MIC LIKE QAMV-VERWMERKM,
        MICDES LIKE QPMT-KURZTEXT,
        UOM TYPE C LENGTH 30,
        METHOD TYPE C LENGTH 43,
        MICMIN TYPE P DECIMALS 2,
        MICMAX TYPE P DECIMALS 2,
        MICMIT TYPE P DECIMALS 2,
        CMICMIT TYPE C LENGTH 17,
        NUMMIC TYPE I,
        NUM(5),
        TYPE TYPE C,
        INSLOT LIKE QALS-PRUEFLOS,
        NOREF LIKE ZQM_LOG_GS-NOREF,
        BARRIER_TYPE TYPE C LENGTH 4,   " MVTR / OTR / blank
      END OF IT_DATA.

DATA: BEGIN OF IT_MIC1 OCCURS 0,
        VBELN LIKE LIPS-VBELN,
        POSNR LIKE LIPS-POSNR,
        CHARG LIKE LIPS-CHARG,
        NOMSR(20),
        NOREF(10),
        ZZTYPE(10),
        MATNR LIKE LIPS-MATNR,
        UECHA LIKE LIPS-UECHA,
        WERKS LIKE LIPS-WERKS,
        MIC LIKE QPMK-MKMNR,
        MICDES LIKE QPMT-KURZTEXT,
        UOM LIKE QPMK-STEUERKZ,
        METHOD(40),
        MICMIN LIKE QPMK-TOLERANZUN,
        MICMAX LIKE QPMK-TOLERANZOB,
        CMICMIT(20),
        MICMIT LIKE QAMR-MITTELWERT,
        INSLOT LIKE QALS-PRUEFLOS,
        MERKNR LIKE QAMV-MERKNR,
        SEQ(1),
        BARRIER_TYPE TYPE C LENGTH 4,   " MVTR / OTR / blank
      END OF IT_MIC1.

DATA: BEGIN OF IT_ZMAP OCCURS 0,
        MATNR LIKE ZMAP_COA-MATNR,
        MIC LIKE ZMAP_COA-MIC,
        KUNNR LIKE ZMAP_COA-KUNNR,     " Customer-specific key
        METHOD LIKE ZMAP_COA-METHOD,
        NUM(5) ,
      END OF IT_ZMAP.

DATA: OK_CODE LIKE SY-UCOMM,
      VBELN LIKE LIPS-VBELN,
      PRODUCT(20),
      NAME1 LIKE KNA1-NAME1,
      NTGEW LIKE LIPS-NTGEW,
      QUANT LIKE LIPS-NTGEW,
      COMPANYTXT(50),
      LF_FM_NAME TYPE RS38L_FNAM,
      WIDTH(50),
      CLENG TYPE I.

DATA: BEGIN OF IT_WIDTH OCCURS 0,
        WIDTH(10),
        CLENG TYPE I,
      END OF IT_WIDTH.

DATA: BEGIN OF IT_DETAIL OCCURS 0,
        CHK TYPE C,
        MIC LIKE QAMV-VERWMERKM,
        NUM(5),
        NUMMIC TYPE I,
        MICDES LIKE QPMT-KURZTEXT,
        UOM TYPE C LENGTH 30,
        METHOD TYPE C LENGTH 43,
        MICMIN TYPE P DECIMALS 2,
        MICMAX TYPE P DECIMALS 2,
        CMICMIT TYPE C LENGTH 17,
        TYPE TYPE C,
      END OF IT_DETAIL.

DATA: BEGIN OF IT_EXPORT OCCURS 0,
        VBELN LIKE LIPS-VBELN,
        UECHA LIKE LIPS-UECHA,
        CHARG LIKE LIPS-CHARG,
        NOMSR(20),
        MATNR LIKE LIPS-MATNR,
        MIC LIKE QPMK-MKMNR,
        MICDES LIKE QPMT-KURZTEXT,
        UOM LIKE QPMK-STEUERKZ,
        METHOD(40),
        MICMIN LIKE QPMK-TOLERANZUN,
        MICMAX LIKE QPMK-TOLERANZOB,
        CMICMIT(20),
      END OF IT_EXPORT.

DATA: BEGIN OF IT_DETAILD OCCURS 0,
        MICDES LIKE QPMT-KURZTEXT,
        UOM LIKE QPMK-STEUERKZ,
        METHOD(40),
        MICMIN LIKE QPMK-TOLERANZUN,
        MICMAX LIKE QPMK-TOLERANZOB,
        CMICMIT(20),
      END OF IT_DETAILD.

DATA: IT_LOT LIKE IT_DATA OCCURS 0 WITH HEADER LINE,
      IT_LOOP LIKE IT_DATA OCCURS 0 WITH HEADER LINE,
      IT_DATA_TMP LIKE IT_DATA OCCURS 0 WITH HEADER LINE.

DATA: BEGIN OF IT_WRONG OCCURS 0,
      CHARG LIKE LIPS-CHARG,
      MIC(1),
      WRONG(1).
DATA: END OF IT_WRONG.

DATA: BEGIN OF L_S_OBJEK,
        OBJEK LIKE AUSP-OBJEK,
        IOBJEK LIKE INOB-OBJEK,
        OBJ(25),
        CHARG LIKE LIPS-CHARG,
      END OF L_S_OBJEK.
DATA: IT_OBJEK LIKE STANDARD TABLE OF L_S_OBJEK WITH HEADER LINE.
DATA: WA_OBJEK LIKE L_S_OBJEK.
DATA: WA_DATA LIKE IT_DATA,
      WA_ZMAP LIKE IT_ZMAP,
      TBATCH LIKE TABLE OF CLBATCH WITH HEADER LINE.
DATA: PRUEF LIKE QALS-PRUEFLOS,
      REF LIKE ZQM_LOG_GS-PRUEFLOSREF.
DATA: IT_MIC LIKE IT_MIC1 OCCURS 0 WITH HEADER LINE,
      IT_MIC2 LIKE IT_MIC1 OCCURS 0 WITH HEADER LINE.

CONTROLS: TCERTI TYPE TABLEVIEW USING SCREEN 0100,
          TDETAIL TYPE TABLEVIEW USING SCREEN 0200.

DATA: V_PROG LIKE ZPROGINFO-PGMNA VALUE 'ZQMI_CERTIFICATE'.

**************************SELECTION SCREEN********************************
SELECTION-SCREEN BEGIN OF BLOCK ABC WITH FRAME TITLE TEXT-ABC.
SELECT-OPTIONS: P_CHARG FOR LIPS-CHARG.
SELECT-OPTIONS: P_ATWRT FOR AUSP-ATWRT.
SELECT-OPTIONS: P_MATNR FOR LIPS-MATNR.
SELECT-OPTIONS: P_VBELN FOR LIPS-VBELN.
SELECT-OPTIONS: P_POSNR FOR LIPS-POSNR.
SELECTION-SCREEN END OF BLOCK ABC.
SELECTION-SCREEN SKIP 2.
SELECTION-SCREEN PUSHBUTTON /12(79) INFO USER-COMMAND INFO.

*&SPWIZARD: LINES OF TABLECONTROL 'TDETAIL'
DATA:     G_TDETAIL_LINES  LIKE SY-LOOPC.
*&SPWIZARD: LINES OF TABLECONTROL 'TCERTI'
DATA:     G_TCERTI_LINES  LIKE SY-LOOPC.
