*&---------------------------------------------------------------------*
*&  Include           ZQMI_CERTIFICATE_F01
*&---------------------------------------------------------------------*
INITIALIZATION.
  MOVE 'Program Information' TO INFO.

AT SELECTION-SCREEN.
  IF SY-UCOMM = 'INFO'.
    PERFORM F_PROG_INFO USING V_PROG.
  ENDIF.

START-OF-SELECTION.
  IF P_CHARG IS INITIAL AND P_ATWRT IS INITIAL
    AND P_MATNR IS INITIAL AND P_VBELN IS INITIAL.
    MESSAGE 'Selection screen tidak boleh kosong!' TYPE 'I'.
  ELSEIF P_POSNR IS NOT INITIAL AND P_VBELN IS INITIAL.
    MESSAGE 'Nomor ODO harus diisi!' TYPE 'I'.
  ELSEIF P_MATNR IS NOT INITIAL AND P_VBELN IS INITIAL.
    MESSAGE 'Nomor ODO harus diisi!' TYPE 'I'.
  ELSE.
    PERFORM GET_DATA.
    SORT IT_DATA BY VBELN CHARG NUMMIC NUM ASCENDING CHK DESCENDING.
    CALL SCREEN 0100.
  ENDIF.

*&---------------------------------------------------------------------*
*&      Form  GET_DATA
*&---------------------------------------------------------------------*
FORM GET_DATA.
  DATA : TEXT1 TYPE C LENGTH 25,
         TEXT2 TYPE C LENGTH 30,
         INSPOPER TYPE BAPI2045L2-INSPOPER,
         ROLL TYPE C LENGTH 10,
         LV_KUNNR LIKE ZMAP_COA-KUNNR.   " Customer key for mapping
  CLEAR : TEXT1, TEXT2, ROLL, LV_KUNNR.

  IF P_CHARG IS INITIAL AND P_ATWRT IS NOT INITIAL.
    CALL FUNCTION 'CONVERSION_EXIT_ATINN_INPUT'
      EXPORTING
        INPUT  = 'ZZNOMORROLL'
      IMPORTING
        OUTPUT = ROLL.

    SELECT OBJEK INTO WA_OBJEK-OBJEK
      FROM  AUSP
      WHERE AUSP~ATINN = ROLL
      AND AUSP~ATWRT IN P_ATWRT
      %_HINTS ORACLE 'INDEX("AUSP~N1")'.
      APPEND WA_OBJEK TO IT_OBJEK.
    ENDSELECT.
    LOOP AT IT_OBJEK INTO WA_OBJEK.
      SELECT SINGLE INOB~OBJEK INTO WA_OBJEK-IOBJEK
      FROM  INOB
      WHERE CUOBJ = WA_OBJEK-OBJEK.
      SPLIT WA_OBJEK-IOBJEK AT SPACE INTO TEXT1 TEXT2.
      CONDENSE: TEXT1, TEXT2.
      WA_OBJEK-OBJ = TEXT1.
      WA_OBJEK-CHARG = TEXT2.
      CLEAR WA_DATA.
      SELECT VBELN POSNR CHARG MATNR WERKS UECHA
        INTO CORRESPONDING FIELDS OF WA_DATA
        FROM LIPS
        WHERE
        LIPS~CHARG = WA_OBJEK-CHARG AND
        LIPS~MATNR IN P_MATNR AND
        LIPS~VBELN IN P_VBELN AND
        LIPS~POSNR IN P_POSNR AND
        ( LIPS~PSTYV = 'ZB' OR LIPS~PSTYV ='ZD' OR LIPS~PSTYV ='ZDN'
        OR LIPS~PSTYV ='ZKB' OR LIPS~PSTYV ='ZKBN' OR LIPS~PSTYV ='ZKBP'
        OR LIPS~PSTYV ='ZKEC' OR LIPS~PSTYV ='ZKEN' OR LIPS~PSTYV ='ZP'
        OR LIPS~PSTYV ='ZRPN' OR LIPS~PSTYV ='ZRPP' OR LIPS~PSTYV ='ZRRN'
        OR LIPS~PSTYV ='ZSPN' OR LIPS~PSTYV ='ZSPP' OR LIPS~PSTYV ='ZTAN'
        OR LIPS~PSTYV ='ZN' OR LIPS~PSTYV ='ZBR' OR LIPS~PSTYV ='ZKRN'
        OR LIPS~PSTYV ='ZKRC' OR LIPS~PSTYV ='ZREC' OR LIPS~PSTYV ='ZREN'
        OR LIPS~PSTYV ='ZRER' OR LIPS~PSTYV ='ZSBS').
        APPEND WA_DATA TO IT_DATA.
      ENDSELECT.
      CLEAR WA_DATA.
      IF P_POSNR-LOW IS NOT INITIAL.
        SELECT VBELN POSNR CHARG MATNR WERKS UECHA
          INTO CORRESPONDING FIELDS OF WA_DATA
          FROM LIPS
          WHERE
          LIPS~CHARG = WA_OBJEK-CHARG AND
          LIPS~MATNR IN P_MATNR AND
          LIPS~VBELN IN P_VBELN AND
          LIPS~UECHA IN P_POSNR AND
          ( LIPS~PSTYV = 'ZB' OR LIPS~PSTYV ='ZD' OR LIPS~PSTYV ='ZDN'
          OR LIPS~PSTYV ='ZKB' OR LIPS~PSTYV ='ZKBN' OR LIPS~PSTYV ='ZKBP'
          OR LIPS~PSTYV ='ZKEC' OR LIPS~PSTYV ='ZKEN' OR LIPS~PSTYV ='ZP'
          OR LIPS~PSTYV ='ZRPN' OR LIPS~PSTYV ='ZRPP' OR LIPS~PSTYV ='ZRRN'
          OR LIPS~PSTYV ='ZSPN' OR LIPS~PSTYV ='ZSPP' OR LIPS~PSTYV ='ZTAN'
          OR LIPS~PSTYV ='ZN' OR LIPS~PSTYV ='ZBR' OR LIPS~PSTYV ='ZKRN'
          OR LIPS~PSTYV ='ZKRC' OR LIPS~PSTYV ='ZREC' OR LIPS~PSTYV ='ZREN'
          OR LIPS~PSTYV ='ZRER' OR LIPS~PSTYV ='ZSBS').
          APPEND WA_DATA TO IT_DATA.
        ENDSELECT.
      ENDIF.
      MODIFY IT_OBJEK FROM WA_OBJEK.
      CLEAR WA_OBJEK.
    ENDLOOP.
  ELSE.
    SELECT VBELN POSNR CHARG MATNR WERKS UECHA
      INTO CORRESPONDING FIELDS OF TABLE IT_DATA
      FROM LIPS
      WHERE
      LIPS~CHARG IN P_CHARG AND
      LIPS~MATNR IN P_MATNR AND
      LIPS~VBELN IN P_VBELN AND
      LIPS~POSNR IN P_POSNR AND
      ( LIPS~PSTYV = 'ZB' OR LIPS~PSTYV ='ZD' OR LIPS~PSTYV ='ZDN'
      OR LIPS~PSTYV ='ZKB' OR LIPS~PSTYV ='ZKBN' OR LIPS~PSTYV ='ZKBP'
      OR LIPS~PSTYV ='ZKEC' OR LIPS~PSTYV ='ZKEN' OR LIPS~PSTYV ='ZP'
      OR LIPS~PSTYV ='ZRPN' OR LIPS~PSTYV ='ZRPP' OR LIPS~PSTYV ='ZRRN'
      OR LIPS~PSTYV ='ZSPN' OR LIPS~PSTYV ='ZSPP' OR LIPS~PSTYV ='ZTAN'
      OR LIPS~PSTYV ='ZN' OR LIPS~PSTYV ='ZBR' OR LIPS~PSTYV ='ZKRN'
      OR LIPS~PSTYV ='ZKRC' OR LIPS~PSTYV ='ZREC' OR LIPS~PSTYV ='ZREN'
      OR LIPS~PSTYV ='ZRER' OR LIPS~PSTYV ='ZSBS').
    CLEAR WA_DATA.
    IF P_POSNR-LOW IS NOT INITIAL.
      SELECT VBELN POSNR CHARG MATNR WERKS UECHA
        INTO CORRESPONDING FIELDS OF WA_DATA
        FROM LIPS
        WHERE
        LIPS~CHARG IN P_CHARG AND
        LIPS~MATNR IN P_MATNR AND
        LIPS~VBELN IN P_VBELN AND
        LIPS~UECHA IN P_POSNR AND
        ( LIPS~PSTYV = 'ZB' OR LIPS~PSTYV ='ZD' OR LIPS~PSTYV ='ZDN'
        OR LIPS~PSTYV ='ZKB' OR LIPS~PSTYV ='ZKBN' OR LIPS~PSTYV ='ZKBP'
        OR LIPS~PSTYV ='ZKEC' OR LIPS~PSTYV ='ZKEN' OR LIPS~PSTYV ='ZP'
        OR LIPS~PSTYV ='ZRPN' OR LIPS~PSTYV ='ZRPP' OR LIPS~PSTYV ='ZRRN'
        OR LIPS~PSTYV ='ZSPN' OR LIPS~PSTYV ='ZSPP' OR LIPS~PSTYV ='ZTAN'
        OR LIPS~PSTYV ='ZN' OR LIPS~PSTYV ='ZBR' OR LIPS~PSTYV ='ZKRN'
        OR LIPS~PSTYV ='ZKRC' OR LIPS~PSTYV ='ZREC' OR LIPS~PSTYV ='ZREN'
        OR LIPS~PSTYV ='ZRER' OR LIPS~PSTYV ='ZSBS').
        APPEND WA_DATA TO IT_DATA.
      ENDSELECT.
    ENDIF.
  ENDIF.
  DELETE IT_DATA WHERE CHARG IS INITIAL.

  " Enhancement: Group by Material (Representative Batch)
  SORT IT_DATA BY VBELN MATNR CHARG.
  DELETE ADJACENT DUPLICATES FROM IT_DATA COMPARING VBELN MATNR.

  LOOP AT IT_DATA.
    CLEAR TBATCH.
    REFRESH TBATCH.

    CALL FUNCTION 'VB_INIT'
      EXPORTING
        INIT_RESET = 'X'.

    CALL FUNCTION 'VB_BATCH_GET_DETAIL'
      EXPORTING
        MATNR              = IT_DATA-MATNR
        CHARG              = IT_DATA-CHARG
        WERKS              = IT_DATA-WERKS
        GET_CLASSIFICATION = 'X'
      TABLES
        CHAR_OF_BATCH      = TBATCH
      EXCEPTIONS
        NO_MATERIAL        = 1
        NO_BATCH           = 2
        NO_PLANT           = 3
        MATERIAL_NOT_FOUND = 4
        PLANT_NOT_FOUND    = 5
        NO_AUTHORITY       = 6
        BATCH_NOT_EXIST    = 7
        LOCK_ON_BATCH      = 8
        OTHERS             = 9.
    READ TABLE TBATCH WITH KEY ATNAM = 'ZZNOMORROLL'.
    IF SY-SUBRC EQ 0.
      IT_DATA-NOMSR = TBATCH-ATWTB.
    ENDIF.
    READ TABLE TBATCH WITH KEY ATNAM = 'ZZCODE'.
    IF SY-SUBRC EQ 0.
      IT_DATA-ZZTYPE = TBATCH-ATWTB.
      CLEAR : IT_ZMAP, LV_KUNNR.
      REFRESH IT_ZMAP.

      " --- ENHANCEMENT: Customer-aware mapping ---
      " Step 1: Ambil KUNNR dari delivery header (LIKP)
      SELECT SINGLE KUNAG INTO LV_KUNNR
        FROM LIKP
        WHERE VBELN = IT_DATA-VBELN.

      " Step 2: Coba customer-specific mapping dulu
      IF LV_KUNNR IS NOT INITIAL.
        SELECT MATNR MIC KUNNR METHOD
          INTO CORRESPONDING FIELDS OF TABLE IT_ZMAP
          FROM ZMAP_COA
          WHERE MATNR    = IT_DATA-MATNR
            AND KUNNR    = LV_KUNNR
            AND DELETION NE 'X'.
      ENDIF.

      " Step 3: Fallback ke general mapping (KUNNR kosong)
      IF IT_ZMAP[] IS INITIAL.
        SELECT MATNR MIC KUNNR METHOD
          INTO CORRESPONDING FIELDS OF TABLE IT_ZMAP
          FROM ZMAP_COA
          WHERE MATNR    = IT_DATA-MATNR
            AND KUNNR    = ' '
            AND DELETION NE 'X'.
      ENDIF.
      " --- END ENHANCEMENT ---

      SORT IT_ZMAP BY MIC ASCENDING.
      DELETE ADJACENT DUPLICATES FROM IT_ZMAP COMPARING MIC.
    ENDIF.
    CLEAR : PRUEF.
    SELECT SINGLE PRUEFLOS INTO PRUEF
      FROM QALS
      WHERE QALS~CHARG = IT_DATA-CHARG
      AND QALS~ART EQ 'Z04'.
    IF SY-SUBRC NE 0.
      CLEAR : REF.
      SELECT SINGLE PRUEFLOSREF INTO REF
        FROM ZQM_LOG_GS
        WHERE CHARGAS = IT_DATA-CHARG.
      SELECT SINGLE PRUEFLOS INTO PRUEF
        FROM ZQM_LOG_GS
        WHERE PRUEFLOSREF = REF
        AND NOSEQ NE 0
        AND NOREF NE 0
        AND PREF NE 0.
    ENDIF.
    PERFORM GET_MIC.
    PERFORM CHECK_WRONG_MAPPING.
    IF IT_DATA-UECHA IS INITIAL.
      IT_DATA-UECHA = IT_DATA-POSNR.
    ENDIF.
    MODIFY IT_DATA.
  ENDLOOP.
  IT_LOT[] = IT_DATA[].
  CLEAR IT_DATA. REFRESH IT_DATA.
  LOOP AT IT_LOT.
    READ TABLE IT_MIC1 WITH KEY VBELN = IT_LOT-VBELN
                                POSNR = IT_LOT-POSNR
                                CHARG = IT_LOT-CHARG.
    IF SY-SUBRC EQ 0.
      LOOP AT IT_MIC1 WHERE VBELN = IT_LOT-VBELN
                        AND POSNR = IT_LOT-POSNR
                        AND CHARG = IT_LOT-CHARG.
        SELECT SINGLE CODE1 INTO IT_MIC1-CMICMIT
          FROM QAMR
          WHERE QAMR~PRUEFLOS = IT_MIC1-INSLOT
          AND QAMR~MERKNR = IT_MIC1-MERKNR.
        IF IT_MIC1-CMICMIT IS INITIAL.
          SELECT SINGLE MITTELWERT INTO IT_MIC1-MICMIT
            FROM QAMR
            WHERE QAMR~PRUEFLOS = IT_MIC1-INSLOT
            AND QAMR~MERKNR = IT_MIC1-MERKNR.
          IT_MIC1-CMICMIT = IT_MIC1-MICMIT.
        ENDIF.

        " --- ENHANCEMENT: Customer-aware METHOD lookup ---
        CLEAR IT_MIC1-METHOD.
        IF LV_KUNNR IS NOT INITIAL.
          SELECT SINGLE METHOD INTO IT_MIC1-METHOD
            FROM ZMAP_COA
            WHERE MATNR    = IT_LOT-MATNR
              AND MIC      = IT_MIC1-MIC
              AND KUNNR    = LV_KUNNR
              AND DELETION NE 'X'.
        ENDIF.
        IF IT_MIC1-METHOD IS INITIAL.
          SELECT SINGLE METHOD INTO IT_MIC1-METHOD
            FROM ZMAP_COA
            WHERE MATNR    = IT_LOT-MATNR
              AND MIC      = IT_MIC1-MIC
              AND KUNNR    = ' '
              AND DELETION NE 'X'.
        ENDIF.
        " --- END ENHANCEMENT ---

        SELECT SINGLE MASSEINHSW INTO IT_MIC1-UOM
          FROM QPMK
          WHERE MKMNR = IT_MIC1-MIC.

        MOVE-CORRESPONDING IT_MIC1 TO WA_DATA.

        " --- ENHANCEMENT: Barrier type detection via CS ---
        CLEAR WA_DATA-BARRIER_TYPE.
        IF WA_DATA-MIC CS 'MVTR' OR WA_DATA-MIC CS 'WVTR'.
          WA_DATA-BARRIER_TYPE = 'MVTR'.
        ELSEIF WA_DATA-MIC CS 'OTR' OR WA_DATA-MIC CS 'O2TR'.
          WA_DATA-BARRIER_TYPE = 'OTR'.
        ENDIF.
        " --- END ENHANCEMENT ---

        APPEND WA_DATA TO IT_DATA.
      ENDLOOP.
    ELSE.
      APPEND IT_LOT TO IT_DATA.
    ENDIF.
  ENDLOOP.

  IT_LOOP[] = IT_DATA[].
  DELETE ADJACENT DUPLICATES FROM IT_LOOP COMPARING CHARG.
  LOOP AT IT_LOOP.
    IT_LOOP-CMICMIT = ''.
    MODIFY IT_LOOP.
  ENDLOOP.
  LOOP AT IT_WRONG WHERE MIC = 'X' OR WRONG = 'X'.
    LOOP AT IT_LOOP WHERE CHARG = IT_WRONG-CHARG.
      MOVE-CORRESPONDING IT_LOOP TO IT_DATA_TMP.
      LOOP AT IT_ZMAP WHERE MATNR = IT_LOOP-MATNR.
        IT_DATA_TMP-MIC = IT_ZMAP-MIC.
        SELECT SINGLE MASSEINHSW INTO IT_DATA_TMP-UOM
          FROM QPMK
          WHERE MKMNR = IT_ZMAP-MIC.
        IT_DATA_TMP-METHOD = IT_ZMAP-METHOD.

        SELECT SINGLE QPMT~KURZTEXT QPMK~TOLERANZOB QPMK~TOLERANZUN
          INTO (IT_DATA_TMP-MICDES, IT_DATA_TMP-MICMAX, IT_DATA_TMP-MICMIN)
          FROM QPMK JOIN QPMT ON QPMK~MKMNR = QPMT~MKMNR
         WHERE QPMK~MKMNR  = IT_ZMAP-MIC
           AND QPMK~WERKS   = IT_LOOP-WERKS
           AND QPMT~SPRACHE = SY-LANGU.

        " --- ENHANCEMENT: Barrier detection untuk fallback rows ---
        CLEAR IT_DATA_TMP-BARRIER_TYPE.
        IF IT_DATA_TMP-MIC CS 'MVTR' OR IT_DATA_TMP-MIC CS 'WVTR'.
          IT_DATA_TMP-BARRIER_TYPE = 'MVTR'.
        ELSEIF IT_DATA_TMP-MIC CS 'OTR' OR IT_DATA_TMP-MIC CS 'O2TR'.
          IT_DATA_TMP-BARRIER_TYPE = 'OTR'.
        ENDIF.
        " --- END ENHANCEMENT ---

        APPEND IT_DATA_TMP TO IT_DATA.
      ENDLOOP.
    ENDLOOP.
  ENDLOOP.
  DELETE IT_DATA WHERE MIC IS INITIAL.

  LOOP AT IT_DATA.
    IT_DATA-CHK = ''.
    IT_DATA-NUMMIC = 2.
    READ TABLE IT_ZMAP WITH KEY MIC = IT_DATA-MIC.
    IF SY-SUBRC EQ 0.
      IT_DATA-CHK = 'X'.
      IT_DATA-NUMMIC = 1.
      IT_DATA-NUM = IT_ZMAP-NUM.
    ENDIF.
    MODIFY IT_DATA.
  ENDLOOP.
  SORT IT_DATA BY VBELN CHK DESCENDING.
ENDFORM.                    "get_data

*&---------------------------------------------------------------------*
*&      Form  GET_MIC
*&---------------------------------------------------------------------*
FORM GET_MIC .
  DATA : ORI1 LIKE ZINSPKEY-PRUEFLOSORI1,
         ORI2 LIKE ZINSPKEY-PRUEFLOSORI2,
         INS  LIKE QALS-PRUEFLOS,
         INS2  LIKE QALS-PRUEFLOS,
         INS3  LIKE QALS-PRUEFLOS,
         INS4  LIKE QALS-PRUEFLOS,
         CTR TYPE I.
  IF PRUEF NE ''.
    SELECT SINGLE PRUEFLOSORI2 INTO ORI2
    FROM ZINSPKEY
      WHERE PRUEFLOSORI2 = PRUEF.
    IF SY-SUBRC NE 0.
      SELECT SINGLE PRUEFLOSORI1 INTO ORI1
        FROM ZINSPKEY
        WHERE PRUEFLOSORI1 = PRUEF.
    ENDIF.
  ENDIF.
  IF ORI2 IS NOT INITIAL.
    CLEAR :IT_MIC,INS,INS2,INS3,INS4.
    SELECT SINGLE PRUEFLOS4 INTO INS
      FROM ZINSPKEY
      WHERE PRUEFLOSORI2 = ORI2.
    IF INS IS NOT INITIAL.
      SELECT  VERWMERKM KURZTEXT TOLERANZUN TOLERANZOB MERKNR
        INTO (IT_MIC-MIC,IT_MIC-MICDES,IT_MIC-MICMIN,IT_MIC-MICMAX,IT_MIC-MERKNR)
        FROM QAMV JOIN QALS ON QALS~PRUEFLOS = QAMV~PRUEFLOS
        WHERE QALS~PRUEFLOS = INS.
        PERFORM COPY.
        IT_MIC-SEQ = 1.
        IT_MIC-INSLOT = INS.
        APPEND IT_MIC.
      ENDSELECT.
      CLEAR CTR.
      CTR = LINES( IT_MIC ).
      IF CTR NE 0.
        APPEND LINES OF IT_MIC FROM 1 TO  CTR TO IT_MIC1.
      ENDIF.
      CLEAR IT_MIC. REFRESH IT_MIC.
    ENDIF.
    CLEAR IT_MIC.
    SELECT SINGLE PRUEFLOS3 INTO INS2
      FROM ZINSPKEY
      WHERE PRUEFLOSORI2 = ORI2.
    IF INS2 IS NOT INITIAL.
      SELECT  VERWMERKM KURZTEXT TOLERANZUN TOLERANZOB MERKNR
        INTO (IT_MIC-MIC,IT_MIC-MICDES,IT_MIC-MICMIN,IT_MIC-MICMAX,IT_MIC-MERKNR)
        FROM QAMV JOIN QALS ON QALS~PRUEFLOS = QAMV~PRUEFLOS
        WHERE QALS~PRUEFLOS = INS2.
        PERFORM COPY.
        IT_MIC-SEQ = 2.
        IT_MIC-INSLOT = INS2.
        APPEND IT_MIC.
      ENDSELECT.
      CLEAR CTR.
      CTR = LINES( IT_MIC ).
      IF CTR NE 0.
        APPEND LINES OF IT_MIC FROM 1 TO  CTR TO IT_MIC2.
      ENDIF.
      CLEAR IT_MIC. REFRESH IT_MIC.
    ENDIF.
    CLEAR IT_MIC.
    SELECT SINGLE PRUEFLOS2 INTO INS3
      FROM ZINSPKEY
      WHERE PRUEFLOSORI2 = ORI2.
    IF INS3 IS NOT INITIAL.                   " Fix: was INS2
      SELECT  VERWMERKM KURZTEXT TOLERANZUN TOLERANZOB MERKNR
        INTO (IT_MIC-MIC,IT_MIC-MICDES,IT_MIC-MICMIN,IT_MIC-MICMAX,IT_MIC-MERKNR)
        FROM QAMV JOIN QALS ON QALS~PRUEFLOS = QAMV~PRUEFLOS
        WHERE QALS~PRUEFLOS = INS3.
        PERFORM COPY.
        IT_MIC-SEQ = 3.
        IT_MIC-INSLOT = INS3.
        APPEND IT_MIC.
      ENDSELECT.
      CLEAR CTR.
      CTR = LINES( IT_MIC ).
      IF CTR NE 0.
        APPEND LINES OF IT_MIC FROM 1 TO CTR TO IT_MIC2.
      ENDIF.
      CLEAR IT_MIC. REFRESH IT_MIC.
    ENDIF.
    CLEAR IT_MIC.
    SELECT SINGLE PRUEFLOS1 INTO INS4
      FROM ZINSPKEY
      WHERE PRUEFLOSORI2 = ORI2.
    IF INS4 IS NOT INITIAL.                   " Fix: was INS2
      SELECT  VERWMERKM KURZTEXT TOLERANZUN TOLERANZOB MERKNR
        INTO (IT_MIC-MIC,IT_MIC-MICDES,IT_MIC-MICMIN,IT_MIC-MICMAX,IT_MIC-MERKNR)
        FROM QAMV JOIN QALS ON QALS~PRUEFLOS = QAMV~PRUEFLOS
        WHERE QALS~PRUEFLOS = INS4.
        PERFORM COPY.
        IT_MIC-SEQ = 4.
        IT_MIC-INSLOT = INS4.
        APPEND IT_MIC.
      ENDSELECT.
      CLEAR CTR.
      CTR = LINES( IT_MIC ).
      IF CTR NE 0.
        APPEND LINES OF IT_MIC FROM 1 TO CTR TO IT_MIC2.
      ENDIF.
      CLEAR IT_MIC. REFRESH IT_MIC.
    ENDIF.
  ELSEIF ORI1 IS NOT INITIAL.
    CLEAR :IT_MIC,INS,INS2,INS3,INS4.
    SELECT SINGLE PRUEFLOS2 INTO INS
      FROM ZINSPKEY
      WHERE PRUEFLOSORI1 = ORI1.
    IF INS IS NOT INITIAL.
      SELECT  VERWMERKM KURZTEXT TOLERANZUN TOLERANZOB MERKNR
        INTO (IT_MIC-MIC,IT_MIC-MICDES,IT_MIC-MICMIN,IT_MIC-MICMAX,IT_MIC-MERKNR)
        FROM QAMV JOIN QALS ON QALS~PRUEFLOS = QAMV~PRUEFLOS
        WHERE QALS~PRUEFLOS = INS.
        PERFORM COPY.
        IT_MIC-SEQ = 1.
        IT_MIC-INSLOT = INS.
        APPEND IT_MIC.
      ENDSELECT.
      CLEAR CTR.
      CTR = LINES( IT_MIC ).
      IF CTR NE 0.
        APPEND LINES OF IT_MIC FROM 1 TO  CTR TO IT_MIC1.
      ENDIF.
      CLEAR IT_MIC. REFRESH IT_MIC.
    ENDIF.
    CLEAR IT_MIC.
    SELECT SINGLE PRUEFLOS1 INTO INS2
      FROM ZINSPKEY
      WHERE PRUEFLOSORI1 = ORI1.
    IF INS2 IS NOT INITIAL.
      SELECT  VERWMERKM KURZTEXT TOLERANZUN TOLERANZOB MERKNR
        INTO (IT_MIC-MIC,IT_MIC-MICDES,IT_MIC-MICMIN,IT_MIC-MICMAX,IT_MIC-MERKNR)
        FROM QAMV JOIN QALS ON QALS~PRUEFLOS = QAMV~PRUEFLOS
        WHERE QALS~PRUEFLOS = INS2.
        PERFORM COPY.
        IT_MIC-SEQ = 2.
        IT_MIC-INSLOT = INS2.
        APPEND IT_MIC.
      ENDSELECT.
      CLEAR CTR.
      CTR = LINES( IT_MIC ).
      IF CTR NE 0.
        APPEND LINES OF IT_MIC FROM 1 TO  CTR TO IT_MIC2.
      ENDIF.
      CLEAR IT_MIC. REFRESH IT_MIC.
    ENDIF.
  ENDIF.
  LOOP AT IT_MIC2.
    READ TABLE IT_ZMAP WITH KEY MIC = IT_MIC2-MIC.
    IF SY-SUBRC NE 0.
      DELETE IT_MIC2 WHERE MIC = IT_MIC2-MIC.
    ENDIF.
  ENDLOOP.
  CLEAR CTR.
  CTR = LINES( IT_MIC2 ).
  IF CTR NE 0.
    APPEND LINES OF IT_MIC2 FROM 1 TO CTR TO IT_MIC1.
  ENDIF.
  CLEAR IT_MIC2. REFRESH IT_MIC2.
ENDFORM.                    " GET_MIC

*&---------------------------------------------------------------------*
*&      Form  CHECK_WRONG_MAPPING
*&---------------------------------------------------------------------*
FORM CHECK_WRONG_MAPPING.
  DATA: V_CHARGJR LIKE ZQM_LOG_GS-CHARGJR,
        V_INSPLOT1 LIKE QALS-PRUEFLOS,
        V_INSPLOT2 LIKE ZINSPKEY-PRUEFLOS1.
  CLEAR : REF, V_CHARGJR, V_INSPLOT1, V_INSPLOT2.

  SELECT SINGLE CHARGJR INTO V_CHARGJR
    FROM ZQM_LOG_GS WHERE CHARGAS = IT_DATA-CHARG.
  SELECT SINGLE PRUEFLOS INTO V_INSPLOT1
    FROM QALS WHERE CHARG = V_CHARGJR.

  SELECT SINGLE PRUEFLOS1 INTO V_INSPLOT2
    FROM ZQM_LOG_GS
    JOIN ZINSPKEY ON ZQM_LOG_GS~PRUEFLOS EQ ZINSPKEY~PRUEFLOSORI1
   WHERE CHARGAS = IT_DATA-CHARG.

  IF V_INSPLOT1 NE V_INSPLOT2.
    IT_WRONG-WRONG = 'X'.
  ENDIF.
  IF IT_MIC1[] IS NOT INITIAL.
    READ TABLE IT_MIC1 WITH KEY CHARG = IT_DATA-CHARG.
    IF SY-SUBRC EQ 0.
      IT_WRONG-MIC = ''.
    ELSE.
      IT_WRONG-MIC = 'X'.
    ENDIF.
  ELSE.
    IT_WRONG-MIC = 'X'.
  ENDIF.

  IT_WRONG-CHARG = IT_DATA-CHARG.
  APPEND IT_WRONG.
  CLEAR IT_WRONG.
ENDFORM.                    "CHECK_WRONG_MAPPING

*&---------------------------------------------------------------------*
*&      Form  COPY
*&---------------------------------------------------------------------*
FORM COPY .
  IT_MIC-VBELN  = IT_DATA-VBELN.
  IT_MIC-POSNR  = IT_DATA-POSNR.
  IT_MIC-CHARG  = IT_DATA-CHARG.
  IT_MIC-NOMSR  = IT_DATA-NOMSR.
  IT_MIC-NOREF  = IT_DATA-NOREF.
  IT_MIC-ZZTYPE = IT_DATA-ZZTYPE.
  IT_MIC-MATNR  = IT_DATA-MATNR.
  IT_MIC-UECHA  = IT_DATA-UECHA.
  IT_MIC-WERKS  = IT_DATA-WERKS.
ENDFORM.                    " COPY

*&---------------------------------------------------------------------*
*&      Form  DOWNLOAD
*&---------------------------------------------------------------------*
FORM DOWNLOAD .
  TABLES RLGRAP.
  DATA:  DEF_PATH LIKE RLGRAP-FILENAME.
  DATA: TMP_FILENAME LIKE RLGRAP-FILENAME.
  DATA V_FILENAME TYPE STRING.
  DATA : BEGIN OF IT_FIELDNAMES OCCURS 0,
           FIELD(30),
         END OF IT_FIELDNAMES.

  REFRESH IT_FIELDNAMES.
  CLEAR IT_FIELDNAMES.
  IT_FIELDNAMES-FIELD = 'Nomor ODO'.     APPEND IT_FIELDNAMES.
  IT_FIELDNAMES-FIELD = 'Item'.          APPEND IT_FIELDNAMES.
  IT_FIELDNAMES-FIELD = 'Batch'.         APPEND IT_FIELDNAMES.
  IT_FIELDNAMES-FIELD = 'Nomor SR'.      APPEND IT_FIELDNAMES.
  IT_FIELDNAMES-FIELD = 'Material'.      APPEND IT_FIELDNAMES.
  IT_FIELDNAMES-FIELD = 'MIC'.           APPEND IT_FIELDNAMES.
  IT_FIELDNAMES-FIELD = 'MIC Description'. APPEND IT_FIELDNAMES.
  IT_FIELDNAMES-FIELD = 'Unit Of Measure'. APPEND IT_FIELDNAMES.
  IT_FIELDNAMES-FIELD = 'Testing Method '. APPEND IT_FIELDNAMES.
  IT_FIELDNAMES-FIELD = 'Lower Limit'.   APPEND IT_FIELDNAMES.
  IT_FIELDNAMES-FIELD = 'Upper Limit'.   APPEND IT_FIELDNAMES.
  IT_FIELDNAMES-FIELD = 'Value'.         APPEND IT_FIELDNAMES.

  CLEAR: IT_EXPORT.
  REFRESH:IT_EXPORT.
  LOOP AT IT_DATA WHERE CHK EQ 'X'.
    CLEAR IT_EXPORT.
    IT_EXPORT-VBELN   = IT_DATA-VBELN.
    IT_EXPORT-UECHA   = IT_DATA-UECHA.
    IT_EXPORT-CHARG   = IT_DATA-CHARG.
    IT_EXPORT-NOMSR   = IT_DATA-NOMSR.
    IT_EXPORT-MATNR   = IT_DATA-MATNR.
    IT_EXPORT-MIC     = IT_DATA-MIC.
    IT_EXPORT-MICDES  = IT_DATA-MICDES.
    IT_EXPORT-UOM     = IT_DATA-UOM.
    IT_EXPORT-METHOD  = IT_DATA-METHOD.
    IT_EXPORT-MICMIN  = IT_DATA-MICMIN.
    IT_EXPORT-MICMAX  = IT_DATA-MICMAX.
    IT_EXPORT-CMICMIT = IT_DATA-CMICMIT.
    APPEND IT_EXPORT.
  ENDLOOP.

  CALL FUNCTION 'WS_FILENAME_GET'
    EXPORTING
      DEF_FILENAME     = RLGRAP-FILENAME
      DEF_PATH         = DEF_PATH
      MASK             = ',*.xls.'
      MODE             = 'S'
      TITLE            = TEXT-011
    IMPORTING
      FILENAME         = TMP_FILENAME
    EXCEPTIONS
      INV_WINSYS       = 01
      NO_BATCH         = 02
      SELECTION_CANCEL = 03
      SELECTION_ERROR  = 04.

  IF SY-SUBRC = 0.
    RLGRAP-FILENAME = TMP_FILENAME.
  ELSE.
    EXIT.
  ENDIF.
  CONCATENATE RLGRAP-FILENAME '.XLS' INTO V_FILENAME.
  CALL FUNCTION 'GUI_DOWNLOAD'
    EXPORTING
      FILENAME              = V_FILENAME
      FILETYPE              = 'ASC'
      WRITE_FIELD_SEPARATOR = 'X'
      CONFIRM_OVERWRITE     = 'X'
      SHOW_TRANSFER_STATUS  = 'X'
    TABLES
      DATA_TAB              = IT_EXPORT
      FIELDNAMES            = IT_FIELDNAMES.

  IF SY-SUBRC <> 0.
    MESSAGE I000(0K) WITH 'Download error'.
    STOP.
  ENDIF.
ENDFORM.                    " DOWNLOAD

*&---------------------------------------------------------------------*
*&      Form  SELALL
*&---------------------------------------------------------------------*
FORM SELALL .
  LOOP AT IT_DATA WHERE CHK NE 'X'.
    IT_DATA-CHK = 'X'.
    MODIFY IT_DATA.
  ENDLOOP.
ENDFORM.                    " SELALL

*&---------------------------------------------------------------------*
*&      Form  DESALL
*&---------------------------------------------------------------------*
FORM DESALL .
  LOOP AT IT_DATA WHERE CHK EQ 'X'.
    IT_DATA-CHK = ''.
    MODIFY IT_DATA.
  ENDLOOP.
ENDFORM.                    " DESALL

*&---------------------------------------------------------------------*
*&      Form  DOWNLOAD_DETAIL
*&---------------------------------------------------------------------*
FORM DOWNLOAD_DETAIL .
  DATA:  DEF_PATH LIKE RLGRAP-FILENAME.
  DATA: TMP_FILENAME LIKE RLGRAP-FILENAME.
  DATA V_FILENAME TYPE STRING.
  DATA : BEGIN OF IT_FIELDNAMES OCCURS 0,
           FIELD(30),
         END OF IT_FIELDNAMES.

  REFRESH IT_FIELDNAMES.
  CLEAR IT_FIELDNAMES.
  IT_FIELDNAMES-FIELD = 'Properties'.      APPEND IT_FIELDNAMES.
  IT_FIELDNAMES-FIELD = 'Unit of Measure'. APPEND IT_FIELDNAMES.
  IT_FIELDNAMES-FIELD = 'Testing Method'.  APPEND IT_FIELDNAMES.
  IT_FIELDNAMES-FIELD = 'Lower Limit'.     APPEND IT_FIELDNAMES.
  IT_FIELDNAMES-FIELD = 'Upper Limit'.     APPEND IT_FIELDNAMES.
  IT_FIELDNAMES-FIELD = 'Value'.           APPEND IT_FIELDNAMES.

  REFRESH IT_DETAILD.
  LOOP AT IT_DETAIL WHERE CHK = 'X'.
    MOVE-CORRESPONDING IT_DETAIL TO IT_DETAILD.
    APPEND IT_DETAILD.
  ENDLOOP.

  CALL FUNCTION 'WS_FILENAME_GET'
    EXPORTING
      DEF_FILENAME     = RLGRAP-FILENAME
      DEF_PATH         = DEF_PATH
      MASK             = ',*.xls.'
      MODE             = 'S'
      TITLE            = TEXT-011
    IMPORTING
      FILENAME         = TMP_FILENAME
    EXCEPTIONS
      INV_WINSYS       = 01
      NO_BATCH         = 02
      SELECTION_CANCEL = 03
      SELECTION_ERROR  = 04.

  IF SY-SUBRC = 0.
    RLGRAP-FILENAME = TMP_FILENAME.
  ELSE.
    EXIT.
  ENDIF.
  CONCATENATE RLGRAP-FILENAME '.XLS' INTO V_FILENAME.
  CALL FUNCTION 'GUI_DOWNLOAD'
    EXPORTING
      FILENAME              = V_FILENAME
      FILETYPE              = 'ASC'
      WRITE_FIELD_SEPARATOR = 'X'
      CONFIRM_OVERWRITE     = 'X'
      SHOW_TRANSFER_STATUS  = 'X'
    TABLES
      DATA_TAB              = IT_DETAILD
      FIELDNAMES            = IT_FIELDNAMES.

  IF SY-SUBRC <> 0.
    MESSAGE I000(0K) WITH 'Download error'.
    STOP.
  ENDIF.
ENDFORM.                    " DOWNLOAD_DETAIL

*&---------------------------------------------------------------------*
*&      Form  SELMAPPING
*&---------------------------------------------------------------------*
FORM SELMAPPING .
  LOOP AT IT_DATA.
    IT_DATA-CHK = ''.
    READ TABLE IT_ZMAP WITH KEY MIC = IT_DATA-MIC.
    IF SY-SUBRC EQ 0.
      IT_DATA-CHK = 'X'.
    ENDIF.
    MODIFY IT_DATA.
  ENDLOOP.
  SORT IT_DATA BY VBELN CHK DESCENDING.
ENDFORM.                    " SELMAPPING

*&---------------------------------------------------------------------*
*&      Form  F_PRINT
*&---------------------------------------------------------------------*
FORM F_PRINT .
  DATA: I_NAST LIKE NAST.
  DATA: I_SSFCOMPOP TYPE SSFCOMPOP.
  DATA: I_SSFCTRLOP  TYPE SSFCTRLOP.
  DATA: I_RECIPIENT          TYPE SWOTOBJID.
  DATA: I_SENDER             TYPE SWOTOBJID.
  DATA: I_ADDR_KEY           LIKE ADDR_KEY.
  DATA: IT_QAMV TYPE QAMV OCCURS 0 WITH HEADER LINE.
  DATA: QUANTITY TYPE CHAR12.

  PERFORM GET_COMPANY_NAME.

  WRITE NTGEW TO QUANTITY DECIMALS 2.
  LOOP AT IT_DETAIL WHERE CHK EQ 'X'.
    IT_QAMV-KURZTEXT   = IT_DETAIL-MICDES.
    IT_QAMV-STEUERKZ   = IT_DETAIL-UOM.
    IT_QAMV-DUMMY40    = IT_DETAIL-METHOD.
    IT_QAMV-TOLERANZOB = IT_DETAIL-MICMIN.
    IT_QAMV-TOLERANZUN = IT_DETAIL-MICMAX.
    IT_QAMV-DUMMY20    = IT_DETAIL-CMICMIT.
    APPEND IT_QAMV.
  ENDLOOP.

  CALL FUNCTION 'SSF_FUNCTION_MODULE_NAME'
    EXPORTING
      FORMNAME           = 'ZQMF_COA'
    IMPORTING
      FM_NAME            = LF_FM_NAME
    EXCEPTIONS
      NO_FORM            = 1
      NO_FUNCTION_MODULE = 2
      OTHERS             = 3.
  CALL FUNCTION LF_FM_NAME
    EXPORTING
      CONTROL_PARAMETERS = I_SSFCTRLOP
      OUTPUT_OPTIONS     = I_SSFCOMPOP
      CUSTOMER           = NAME1
      DELIVERY           = VBELN
      PRODUCT            = PRODUCT
      QUANTITY           = QUANTITY
      WIDTH              = WIDTH
      COMPANYTXT         = COMPANYTXT
    TABLES
      IT_QAMV            = IT_QAMV
    EXCEPTIONS
      FORMATTING_ERROR   = 1
      INTERNAL_ERROR     = 2
      SEND_ERROR         = 3
      USER_CANCELED      = 4
      OTHERS             = 5.
ENDFORM.                    " F_PRINT

*&---------------------------------------------------------------------*
*&      Form  GET_COMPANY_NAME
*&---------------------------------------------------------------------*
FORM GET_COMPANY_NAME.
  DATA:ZWERKS LIKE LIPS-WERKS,
       ZVBELN LIKE LIPS-VBELN.

  IF VBELN IS NOT INITIAL.
    CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
      EXPORTING
        INPUT  = VBELN
      IMPORTING
        OUTPUT = ZVBELN.
    SELECT SINGLE WERKS FROM LIPS INTO ZWERKS WHERE VBELN EQ ZVBELN.
  ELSE.
    MESSAGE 'Nomor ODO tidak ada!' TYPE 'I'.
    STOP.
  ENDIF.

  SELECT SINGLE T001~BUTXT FROM T001
    JOIN T001K ON T001~BUKRS EQ T001K~BUKRS INTO COMPANYTXT
    WHERE T001K~BWKEY EQ ZWERKS.
ENDFORM.                    "GET_COMPANY_NAME
